#!/bin/bash

CONFIG_FILE="${HOME}/.config/dune-os/toolbox.ini"
if [ -f "$CONFIG_FILE" ]; then
  /usr/bin/distrobox assemble create -v --file "$CONFIG_FILE"
elif [ -f /usr/share/dune-os/toolbox.ini ]; then
  /usr/bin/distrobox assemble create -v --file /usr/share/dune-os/toolbox.ini
else
  echo "Can't find toolbox.ini configuration file..."
  exit 1
fi
